### ISSUE TITLE
Debug CUDA

### ISSUE THREAD

**Issue by zsz-pro** [city-super/Scaffold-GS#10]
Nice work！
想请教一个比较通用的问题，写CUDA的时候，一般是用下面这种方法进行调试吗？请指点下~
![image](https://github.com/city-super/Scaffold-GS/assets/61933660/f315adab-935f-4b45-be0e-68ba1d439893)

**Comment by inspirelt** [comment]
谢谢. 

我debug cuda时, 一般是在cuda内部添加printf语句. 比较原始, 但还挺有效的哈哈. 其它高级的debug方法我也不太熟悉.

**Comment by zsz-pro** [comment]
了解了~谢谢
