### ISSUE TITLE
Which parameter modified to obtain finer structure and higher PNSR ?

### ISSUE THREAD

**Issue by 1346052851** [city-super/Scaffold-GS#11]
thank your Scaffold-GS , i like it very much !!!

Which parameter modified to obtain finer structure and higher PNSR ?

**Comment by inspirelt** [comment]
Thanks for your appreciation. For a finer structure, you may try a smaller ```voxel_size```, or a smaller ```update_init_factor```(satisfies 2^x), or smaller ```update_hierachy_factor```, or larger ```update_depth```. Meanwhile, a finer structure does not always contributes to a higher PSNR. It depends on the specific data.
