### ISSUE TITLE
PSNR about Mip-NeRF360

### ISSUE THREAD

**Issue by wenkaier** [city-super/Scaffold-GS#12]
The original paper (3DGS) is 27.21. In your paper, it is 28.69. What processing did you do?

**Comment by inspirelt** [comment]
The original 3dgs is averaged on all 9 scenes of mip360. However, the data of scene ```treehill``` and ```flowers``` were not public, previously. So our reported result is averaged on the rest 7 scenes.

**Comment by zsz-pro** [comment]
scenes = ["bicycle", "bonsai", "counter", "flowers", "garden", "stump", "treehill", "kitchen", "room"]
factors = [4, 2, 2, 4, 4, 4, 4, 2, 2]
The above experiment setup is for mip-splatting on the Mip-NeRF360 dataset. I would like to ask if the table results provided in your article are also under this experimental setup?
![image](https://github.com/city-super/Scaffold-GS/assets/61933660/572783ba-c332-47b4-ab86-de20b4156ce7)

**Comment by inspirelt** [comment]
No. We did not set the resolution factor, details can be found in ```train.sh``` and ```train_mip360.sh```.

**Comment by zsz-pro** [comment]
OK！Thansks！



---- Replied Message ----
| From | Tao ***@***.***> |
| Date | 01/14/2024 02:07 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [city-super/Scaffold-GS] PSNR about Mip-NeRF360 (Issue #12) |

No. We did not set the resolution factor, details can be found in train.sh and train_mip360.sh.
