### ISSUE TITLE
Reproduce synthetic nerf result

### ISSUE THREAD

**Issue by nfyfamr** [city-super/Scaffold-GS#13]
Thanks for sharing this nice code.
I am trying to reproducing the result on the synthetic nerf. 
I found that there is no predefined configuration for it, so I used the default settings from `sing_train.sh` file like,

> scene='nerf_synthetic/lego'
> exp_name='lego'
> voxel_size=0.01
> update_init_factor=16
> gpu=3
> 
> ./train.sh -d ${scene} -l ${exp_name} --gpu ${gpu} --voxel_size ${voxel_size} --update_init_factor ${update_init_factor}

After 30k iterations I got 32.05 dB for the lego scene, which is 3.64 dB lower than that in your paper. I think the default setting I used is not optimal training options. Could you share your testing options?

**Comment by inspirelt** [comment]
Hi, @nfyfamr , for synthetic nerf, we try two strategies. One is to train with ```voxel_size=0.0001, update_init_factor=8```. The other is, first train with ```voxel_size=0.0, update_init_factor=16```, and then use  the ```point_cloud.ply``` as the initial point to rerun the training process (rename+copy). Both strategies achieve similar quality while the latter enjoys a smaller storage and faster inference speed. So we adopt the latter in the paper, as described in section 4.2 (p6~p7).

**Comment by inspirelt** [comment]
The training scripts are released.

**Comment by nfyfamr** [comment]
Thanks for your response!
