### ISSUE TITLE
Floaters in Free Camera Trajectories scenes

### ISSUE THREAD

**Issue by haksorus** [city-super/Scaffold-GS#14]
Hello!
I have tried to use Scaffold-GS to render scenes with Free Camera Trajectories from F2-NeRF dataset (https://totoro97.github.io/projects/f2-nerf/).

The rendering of train/test camera views works fine, but when I want to create new views from the side (changing T vector), a lot of floating gaussians appear.

Here example below:
Render           |  SfM point cloud
:-------------------------:|:-------------------------:
![](https://github.com/city-super/Scaffold-GS/assets/69139386/fb86ab02-5103-4fbd-8c92-0eef71a5f980)  |  ![](https://github.com/city-super/Scaffold-GS/assets/69139386/f41db0a3-8eae-454d-8978-64acd65868da)

It is worth noting that the point cloud from sfm is quite sparse, but how to avoid the appearance of floaters for such scenes?

**Comment by inspirelt** [comment]
Hi, thanks for evaluating on the challenging setting. I think two methods may reduce floaters: 1. post-process the saved gaussians to remove those outliers; 2. regularize with depth prior. And, some techniques designed for sparse view settings may also work. Further discussions are welcome.

**Comment by haksorus** [comment]
I will try it, thank you!
