### ISSUE TITLE
When will you release your rendering tool? 

### ISSUE THREAD

**Issue by umarkhalidAI** [city-super/Scaffold-GS#17]
I ran the network viewer once my training is started but it didn't automatically pick the training. Do I need to pass any additional command line arguments?
`SIBR_viewers/install/bin/SIBR_gaussianViewer_app` doesn't seem to pick the training. I have the training in the same machine but SIBR app is in different directory. 
Also for rendering, why we can't just use the SIBR viewer from original Gaussian splatting authors?

**Comment by inspirelt** [comment]
Sorry for late reply. The viewer is available now.
