### ISSUE TITLE
Question about anchor adjustment

### ISSUE THREAD

**Issue by chenjiajie9811** [city-super/Scaffold-GS#19]
Hi, thank you for your great work!

With your anchor growing and pruning design, do you think if it exists such a case that all neural gaussians from one anchor will be moved to the voxel of another anchor. In this case you will not prune the first anchor because the opacity values of the GS from that anchor are still large enough. Just like the picture from your paper, there are some anchors floating around the object. Or is this acceptable? Maybe I have understand it wrong, please correct me. 
![image](https://github.com/city-super/Scaffold-GS/assets/101929927/154ef1f2-50ec-41b2-94e4-bb6eeadd18ca)

Thanks!

**Comment by inspirelt** [comment]
Hi, thanks for your interests. This is a good question. And your concern is totally possible. The gaussian density is constrained by the voxel size and ```n_offsets```, such floating anchors may serve as supplementary to those texture-rich area. So, it's acceptable and reasonable to a certain extent. However, it could potentially lead to inefficiencies in managing and allocating the representation resources.
