### ISSUE TITLE
Question of the effectiveness of the appearance embedding in Scaffold-GS.

### ISSUE THREAD

**Issue by LZleejean** [city-super/Scaffold-GS#20]
Great work. 
Could you provide some results for the effectiveness of the appearance embedding. When I eable it.

**Comment by tongji-rkr** [comment]
The second example in the viewer (https://drive.google.com/file/d/1R53SD7oE-56-PWKjRhHdsnQxNSJyFvPw/view?usp=sharing) is our result of one of training scenes in IMW 2020 (https://www.cs.ubc.ca/research/image-matching-challenge/2020/leaderboard/). You can adjust the appearance embedding to get the effect of day or night. You can also test the reconstruction effect on other scenes in the dataset or take a series of images with different exposures.

**Comment by iampalop** [comment]
Where I can adjust the appearance embedding?

**Comment by inspirelt** [comment]
It can be adjusted by feeding the ```apearance_dim``` argument, like https://github.com/city-super/Scaffold-GS/blob/971b68177a0774fc840a12130360344d2a7ab382/train_mip360.sh#L5, where ```0``` denotes not using it, other number like ```32``` denotes a 32-channel appearance embedding.

**Comment by iampalop** [comment]
Thank you so much, wolud you mind to explain me more about appearance embedding and its number or tell me where I can read about it.

**Comment by inspirelt** [comment]
More about it can be found in "NeRF in the wild"(https://arxiv.org/abs/2008.02268).
