### ISSUE TITLE
nvrtc: error: invalid value for --gpu-architecture (-arch)

### ISSUE THREAD

**Issue by Lee-JaeWon** [city-super/Scaffold-GS#23]
Thanks for the great work.

I tried to run the code in `single_train.sh` with colmap data.

However, I got the following error

```
  }
};

extern "C"
__launch_bounds__(512, 4)
__global__ void reduction_prod_kernel(ReduceJitOp r){
  r.run();
}
nvrtc: error: invalid value for --gpu-architecture (-arch)

Training progress:   0%|                                                   | 0/30000 [00:00<?, ?it/s]
```

What could be the problem?

**Comment by wangyuyy** [comment]
I have encountered a similar issue before, which is likely due to the torch version not recognizing certain GPU operations. For me, with torch 1.12.1-cu113, `torch.prod()` cannot be used on the RTX 4090. You need to check the Python error message above the CUDA error message to see which function is throwing the error. Then, you can transfer this tensor to the CPU first and then back to the GPU.

**Comment by Lee-JaeWon** [comment]
Good. I'll look at the torch and cuda version and reconfigure it.

So if I have `colmap_data/images`, `colmap_data/sparse`, I should run `single_train.sh`, right?

**Comment by inspirelt** [comment]
If it's a issue with ```torch.prod()```, unfold the ```scaling.prod(dim=1)``` into ```scaling[:,0]*scaling[:,1]*scaling[:,2]``` may be an direct solution.

**Comment by Lee-JaeWon** [comment]
@inspirelt it works well to me! Thanks.

But to my dismay, I keep running into problems.

```
Number of points at initialisation :  7610 [06/03 03:56:24]
Training progress:   0%|                                                   | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 528, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), dataset,  args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, wandb, logger)
  File "train.py", line 148, in training
    loss.backward()
  File "/opt/conda/envs/scaffold_gs/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/envs/scaffold_gs/lib/python3.7/site-packages/torch/autograd/__init__.py", line 166, in backward
    grad_tensors_ = _make_grads(tensors, grad_tensors_, is_grads_batched=False)
  File "/opt/conda/envs/scaffold_gs/lib/python3.7/site-packages/torch/autograd/__init__.py", line 67, in _make_grads
    raise RuntimeError("grad can be implicitly created only for scalar outputs")
RuntimeError: grad can be implicitly created only for scalar outputs
Training progress:   0%|                                                   | 0/30000 [00:00<?, ?it/s]

```

**Comment by inspirelt** [comment]
It seems like you add a tensor into the loss. Have you reduced the multiplication results with a ```.mean()```?

**Comment by Lee-JaeWon** [comment]
@inspirelt Yes I just put the `.mean()`in and I was able to do the training.
Thanks for your help.

**Comment by inspirelt** [comment]
Great!

**Comment by WangPu1999** [comment]
我也遇到了相同的问题，一度让我很沮丧。感谢您的解答，让我解决了这个问题成功开始运行训练脚本！

**Comment by chensh1127** [comment]
hey, I have encountered a similar issue before. I run the code "single_train.sh", and the error is 
<img width="692" alt="截屏2024-09-25 22 17 22" src="https://github.com/user-attachments/assets/5877d55d-d888-4980-9b20-ea27170deeff">

my cuda version is 11.6 and the torch version is 1.21.1.
<img width="877" alt="截屏2024-09-25 22 16 19" src="https://github.com/user-attachments/assets/44f5e5d6-18c1-4238-930f-7c18a0c79f5c">

**Comment by LivingTom** [comment]
> If it's a issue with `torch.prod()`, unfold the `scaling.prod(dim=1)` into `scaling[:,0]*scaling[:,1]*scaling[:,2]` may be an direct solution.
thanks a lot , this is work for me.
