### ISSUE TITLE
error about building SIBR in the project

### ISSUE THREAD

**Issue by cv-lab-x** [city-super/Scaffold-GS#28]
thanks for your great work,  some errors about building SIBR 

`Scaffold-GS/SIBR_viewers/src/projects/gaussianviewer/renderer/GaussianView.cpp:550:53: error: ‘visible_filter’ is not a member of ‘CudaRasterizer::Rasterizer’
  550 |                         CudaRasterizer::Rasterizer::visible_filter(
      |                                                     ^~~~~~~~~~~~~~
Scaffold-GS/SIBR_viewers/src/projects/gaussianviewer/renderer/GaussianView.cpp:556:68: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
  556 |                                 ak_pos_all.contiguous().data<float>(),
`

looking forward to your reply, thanks! @inspirelt

**Comment by tongji-rkr** [comment]
Thank you for your reminder. We have modified the part of **diff-gaussian-rasterization**, please use the content in https://github.com/tongji-rkr/diff-gaussian-rasterization.git as replacement, and we will modify it in CMakeLists.txt later.
