### ISSUE TITLE
Please!!  When to Relase your code?

### ISSUE THREAD

**Issue by Contrail97** [city-super/Scaffold-GS#3]
Hi, sorry to bother you, I'm very inspired by your work, however, I encountered some problems when trying to reproduce the paper, so when will you release your code?

**Comment by inspirelt** [comment]
Thanks for your attention. We have just completed cleaning the code and are now conducting some final tests. We expect to release it by tomorrow.

**Comment by inspirelt** [comment]
Released. Feel free to contact me if you have other questions.
