### ISSUE TITLE
error about the prebuild viewer on window

### ISSUE THREAD

**Issue by cv-lab-x** [city-super/Scaffold-GS#32]
hi, thanks for your great work, i got the errors when using the prebuild viewer on window,
cuda 11.4 RTX3080 

` LINE 720, FUNC sibr::GaussianView::onRenderIBR
                        A CUDA error occurred during rendering:an illegal memory access was encountered. Please rerun in Debug to find the exact line!` 

looking forward to your reply, thanks!

**Comment by inspirelt** [comment]
OK. We will check it after submitting the ECCV supp.

**Comment by tongji-rkr** [comment]
Could you provide the specific information about the terminal command and the scene you selected?

**Comment by cv-lab-x** [comment]
> Could you provide the specific information about the terminal command and the scene you selected?
 the origin SIBR with origin 3dgs model  work well on my pc.

i use the pre-trained model you provided, the link , [kitchen](https://drive.google.com/file/d/1mVpkepG7mL9HYJeIbdmpo7XQjhrVU20A/view?usp=sharing) in the Mip-NeRF 360 Dataset; 

command:
` .\bin\SIBR_gaussianViewer_app.exe -m ..\exp1\ckpt\ ` 
Looking forward to your reply, thanks! @tongji-rkr

**Comment by tongji-rkr** [comment]
.\bin\SIBR_gaussianViewer_app.exe -m ..\exp1\ckpt\ -s ..\exp1\data\

**Comment by cv-lab-x** [comment]
> Please add source path.
yes, add the source path, the all prints are below:

`PS D:\Scaffold_GS_viewer\viewer> .\bin\SIBR_gaussianViewer_app.exe -m ..\exp1\ckpt\ -s ..\exp1\data\
[SIBR] --  INFOS  --:   Initialization of GLFW
[SIBR] --  INFOS  --:   OpenGL Version: 4.6.0 NVIDIA 451.48[major: 4, minor: 6]
[SIBR] --  INFOS  --:   Dataset type:
Number of input Images to read: 279
Number of Cameras set up: 279
LOADSFM: Try to open ..\exp1\data\/sparse/0/points3D.bin
Num 3D pts 241367
[SIBR] --  INFOS  --:   SfM Mesh '..\exp1\data\/sparse/0/points3d.bin successfully loaded.  (241367) vertices detected. Init GL ...
[SIBR] --  INFOS  --:   Init GL mesh complete
[SIBR] --  INFOS  --:   Loading 334093 Anchor points
[SIBR] --  INFOS  --:   opacity_mlp : 1
[SIBR] --  INFOS  --:   cov_mlp : 1
[SIBR] --  INFOS  --:   color_mlp : 1
[SIBR] --  INFOS  --:   embedding_appearance : 0
[SIBR] --  INFOS  --:   Initializing Raycaster
[SIBR] --  INFOS  --:   Interactive camera using (0.009,1100) near/far planes.
Switched to trackball mode.
[SIBR] ##  ERROR  ##:   FILE F:\SIBR_viewers\src\projects\gaussianviewer\renderer\GaussianView.cpp
                        LINE 720, FUNC sibr::GaussianView::onRenderIBR
                        A CUDA error occurred during rendering:an illegal memory access was encountered. Please rerun in Debug to find the exact line!`
@tongji-rkr

**Comment by tongji-rkr** [comment]
This is weird and I think it's the CUDA version because I didn't test it on any environments below 11.6

**Comment by tongji-rkr** [comment]
In addition, what is your Windows version?

**Comment by cv-lab-x** [comment]
> In addition, what is your Windows version?

win11 cuda11.4 rtx3080

**Comment by cv-lab-x** [comment]
it works well on cuda 11.6
