### ISSUE TITLE
error about building SIBR in the project

### ISSUE THREAD

**Issue by lcl124252** [city-super/Scaffold-GS#35]
Thank you for your great work! The src/core under SIBR you provided does not have the view folder, but there is the add_subdirectory(core/view) code under cmakelist. I would like to know whether this view folder is necessary?

**Comment by lcl124252** [comment]
Or do I want to know if the view folder I got from another SIBR project is available?

**Comment by lcl124252** [comment]
我解决了问题，事实证明就是其他SIBR_viewer的view文件夹可以直接拿过来使用，放在src/core/这里就可以了

**Comment by cv-lab-x** [comment]
> 我解决了问题，事实证明就是其他SIBR_viewer的view文件夹可以直接拿过来使用，放在src/core/这里就可以了

on windows or ubuntu?

**Comment by lcl124252** [comment]
> > 我解决了问题，事实证明就是其他SIBR_viewer的view文件夹可以直接拿过来使用，放在src/core/这里就可以了
> 
> on windows or ubuntu?

windows
