### ISSUE TITLE
can't see the generated result

### ISSUE THREAD

**Issue by lcl124252** [city-super/Scaffold-GS#36]
I tried to use the compiled SIBR_viewer provided by you, and the SIBR_viewer compiled by myself, and both ended up with a white screen and a flash back. This is what it shows:
[SIBR] --  INFOS  --:   OpenGL Version: 4.6.0 NVIDIA 537.34[major: 4, minor: 6]
[SIBR] --  INFOS  --:   Dataset type:
Number of input Images to read: 257
Number of Cameras set up: 257
LOADSFM: Try to open C:\Users\lcl124252\Desktop\code\Scaffold-GS\data\mydataset\scene1/sparse/0/points3D.bin
Num 3D pts 65407
[SIBR] --  INFOS  --:   SfM Mesh 'C:\Users\lcl124252\Desktop\code\Scaffold-GS\data\mydataset\scene1/sparse/0/points3d.bin successfully loaded.  (65407) vertices detected. Init GL ...
[SIBR] --  INFOS  --:   Init GL mesh complete
[SIBR] --  INFOS  --:   Loading 251516 Anchor points
[SIBR] --  INFOS  --:   opacity_mlp : 0
[SIBR] --  INFOS  --:   cov_mlp : 0
[SIBR] --  INFOS  --:   color_mlp : 0
[SIBR] --  INFOS  --:   embedding_appearance : 0

**Comment by lcl124252** [comment]
我已经解决了问题，iteration_30000里的这三个文件要放在这里
![$7 $H5 20OS4PCKV693SAP](https://github.com/city-super/Scaffold-GS/assets/70134213/c5f9ead1-f640-43e4-b59f-b6d8eee91f88)
同时iteration_30000的点云文件要放在这里
![CERDZ}JINY4TQE}9)CI{7VR](https://github.com/city-super/Scaffold-GS/assets/70134213/c3934f31-980a-4ffd-9394-683a464fbd2c)

**Comment by LucretiaLuo** [comment]
Thanks a lot for the solution! This has been bothering me for some time. Just one thing to mention that the original iteration_30000 folder should be deleted otherwise the correct result won't come out.
