### ISSUE TITLE
Actual training speed

### ISSUE THREAD

**Issue by kwea123** [city-super/Scaffold-GS#4]
The training converges faster in terms of iterations, how about the actual speed (time)? Since you use mlps to decode the features (and the features are multi-res), I assume the training speed per iteration is slower than 3DGS. So how does the graph look like if we compare with 3DGS with time in x-axis and psnr in y-axis?

**Comment by inspirelt** [comment]
Hi. The graph looks similar if let the x-axis be time. Because, 1. the tiny MLP is not as slow as assumed; 2. gaussians grows rapidly in 3D-GS, so it is faster at the early stage but slower in the final stage, which leads to a similar average speed in our machine.

**Comment by kwea123** [comment]
I tried on one custom scene, the time to reach 30k step is:
- 7:36 for original
- 10:22 for this repo
So I think in terms of time it is still slower, if we care about time to reach a certain psnr score, it needs further investigation.
