### ISSUE TITLE
Training on 4K resolution

### ISSUE THREAD

**Issue by bernard0047** [city-super/Scaffold-GS#40]
Hi! I'm trying to train on scenes with higher resolution, but getting worse results. What changes/optimizations do you suggest to achieve better reconstruction on 2K or 4K images?

Thanks!

**Comment by inspirelt** [comment]
Hi, could you clarify if the 'worse results' are in comparison to Scaffold's performance on lower resolution images or against 3D-GS in the same higher resolution?

**Comment by yangjiheng** [comment]
> Hi! I'm trying to train on scenes with higher resolution, but getting worse results. What changes/optimizations do you suggest to achieve better reconstruction on 2K or 4K images?
> 
> Thanks!

I believe there is a control in CameraUtil to prevent training and evaluating resolution go beyond 1600 (in width), therefore, if you try to extend the resolution, you have to change that part.

GPU memory increase quickly using higher resolution.

**Comment by bernard0047** [comment]
I am aware of that flag. 2K images training takes a very high memory. @inspirelt I meant the 'worse results' were as compared to Scaffold's performance on 1K resolution. I tried tweaking some hyperparameters like `update_hierachy_factor, update_init_factor, update_depth, voxel_size, n_offsets, appearance_dim` but got no success. 

There's a similar trend in the 3D-GS pipeline too I agree.

**Comment by inspirelt** [comment]
Did you try to train for longer iterations? Since more details are presented in a higher resolution image, Scaffold-GS may need more growing operations.

**Comment by leelele-cug** [comment]
@bernard0047 Hi, I found the same issue in Octree-GS, which is based on Scaffold-GS. 
Have you find the solution or reason?

**Comment by bernard0047** [comment]
Actually my intrinsics were wrong. With correct intrinsics I get slightly better results with higher resolution

**Comment by leelele-cug** [comment]
> Actually my intrinsics were wrong. With correct intrinsics I get slightly better results with higher resolution

Hi, thanks for your attention and reply.  

I'm still encountering with this problem. 
Do you mean the intrinsics should be changed when we change the training resolution?
or
You just used correct intrinsics for 1.6K but use another wrong intrinsics(which suppose to be the same with 1.6K) for 4K?

**Comment by bernard0047** [comment]
We don't need to change intrinsics if we use a larger image. Just make sure that Cx and Cy are calculated correctly (W/2, H/2) from bigger image. 

My intrinsics were wrong due to some other bug and is an unrelated issue (solved)

**Comment by leelele-cug** [comment]
> We don't need to change intrinsics if we use a larger image. Just make sure that Cx and Cy are calculated correctly (W/2, H/2) from bigger image.
> 
> My intrinsics were wrong due to some other bug and is an unrelated issue (solved)

OK, I got it, thanks a lot.
