### ISSUE TITLE
Question for get the size

### ISSUE THREAD

**Issue by shisheidexinya** [city-super/Scaffold-GS#41]
![)3~NYHT{5IN)S2Q 0SD%5Q](https://github.com/city-super/Scaffold-GS/assets/156766260/074d1bd3-0a0c-4461-9444-60216932b9e5)
hello，it's a great work! and i want to konw how to get the Mem. when i run this work, i didn't get the Mem from the result.
Thanks

**Comment by inspirelt** [comment]
Hi, the Mem refers to the .ply file's storage size obtained by ```du -sh filepath```. Due to some minor updates in the current repo, some minor differences from the paper are acceptable.

**Comment by shisheidexinya** [comment]
thank you for your reply.
best wishes!

**Comment by inspirelt** [comment]
Thanks.
