### ISSUE TITLE
Testing accuracy gap

### ISSUE THREAD

**Issue by wyf0912** [city-super/Scaffold-GS#45]
Thanks for your great work!

Did you meet the problem that the testing accuracy is much lower than the training one?
My reproduced test PSNR is only 19.75 (25.34 in the paper) while the training PSNR is the same as the paper.

I repeated the experiment many times but the problem always exists. 

Looking for your reply.

![132501712754502_ pic](https://github.com/city-super/Scaffold-GS/assets/26561397/a11336a3-6711-436a-9845-aa2f10763a1c)

**Comment by inspirelt** [comment]
Hi, please follow https://github.com/city-super/Scaffold-GS/blob/3a2cc331b4cc54e056033353678600fd27cc535b/arguments/__init__.py#L73 to set the dist-related parameters. We will update the inconvenient configuration system as soon as possible.

**Comment by wyf0912** [comment]
Thanks for your reply. I solved the problem by updating the CUDA.
