### ISSUE TITLE
train without mlp

### ISSUE THREAD

**Issue by cv-lab-x** [city-super/Scaffold-GS#46]
hi, thanks for your great work, is it possible to modify anchor points without mlp in order to change scaffold-gs to explicit model? in unity / UE or other applications
@tongji-rkr 
Looking forward to your reply, thanks!

**Comment by inspirelt** [comment]
Hi, thanks for recognizing that the MLP is not essential in scaffold. We considered removing mlp but it will lead to performance degradation.

**Comment by cv-lab-x** [comment]
> Hi, thanks for recognizing that the MLP is not essential in scaffold. We considered removing mlp but it will lead to performance degradation.

performance degradation? you mean the quality or the rendering speed? have you already tested ? @inspirelt

**Comment by inspirelt** [comment]
The opacity mlp dominates the gaussian selection process, so removing it will has an impact on the rendering speed.
