### ISSUE TITLE
SIBR can't render ellipsoids from the floating menu

### ISSUE THREAD

**Issue by WillYao-THU** [city-super/Scaffold-GS#47]
Hi, Thanks for your great work! 

I found there is no ellipsoids option in the floating menu

Looking forward to your reply, thanks!

![微信图片_20240425170706](https://github.com/city-super/Scaffold-GS/assets/135940893/dd464b2e-a6ba-479b-819e-85c7767a4055)

**Comment by tongji-rkr** [comment]
Unlike 3D-GS, Scaffold-GS renders Gaussians at different views with **variations** and thus does not match this pattern.

**Comment by WillYao-THU** [comment]
Thanks for your explanation, I got it !
