### ISSUE TITLE
submodules not defined

### ISSUE THREAD

**Issue by kwea123** [city-super/Scaffold-GS#5]
There is no `.gitmodule` file, I don't know which version of `diff_gaussian_rasterization` you are using. There seems to be a `visible_filter` function that you added on top of the original code.

https://github.com/city-super/Scaffold-GS/blob/aa7ac5e8e3c31bc615042524fea1ca3aac8a1023/gaussian_renderer/__init__.py#L215-L218

this function cannot be found

**Comment by inspirelt** [comment]
Thanks for reminding. Now the submodule is available.
