### ISSUE TITLE
There are many floating objects in the air

### ISSUE THREAD

**Issue by whx-code** [city-super/Scaffold-GS#54]
Hello, why is there so much floating debris in the sky in my reconstruction results (30000 iterations)? I guess this is related to my use of Geo-registration when generating sparse point clouds. My initial point cloud is in the enu coordinate system (belonging to the Cartesian coordinate system), measured in meters. How should I adjust? Looking forward to your reply.
![20240529004530](https://github.com/city-super/Scaffold-GS/assets/128272526/80a2849a-8032-4d20-bdc8-1642ef25833d)
![20240529004417](https://github.com/city-super/Scaffold-GS/assets/128272526/c44ecaf1-e3ba-455d-aefb-0bc312e348f7)
![20240529004443](https://github.com/city-super/Scaffold-GS/assets/128272526/14f06776-92d1-4891-95fb-5af1410d9f31)

**Comment by inspirelt** [comment]
Hello, two suggestions:

1. do a post-check to eliminate gaussian only visible in few views, which can reduce floaters (I will add the related code in a few days, or you can implement this idea by yourself if in a hurry.);
2. set a large ```self.update_from``` to stabilize the early scene structure.

Hope these help you!
