### ISSUE TITLE
How much gpu memory is needed

### ISSUE THREAD

**Issue by MuQoe** [city-super/Scaffold-GS#56]
i was using a 4090 for trainning but encounter cuda memory error（allocate 34gb for a single image？）， not sure if this is common since i also got error about cuda memory illegal access

**Comment by inspirelt** [comment]
You can set the data_device to 'cpu' to reduce the memory consumption. See https://github.com/city-super/Scaffold-GS/blob/47ac423fa25ac91c17380a6f138dbefd0d23b635/arguments/__init__.py#L63 . The cuda memory illegal access may be a dependency-version-related issue.
