### ISSUE TITLE
Questions about Anchor update policy.

### ISSUE THREAD

**Issue by WeihangLiu2024** [city-super/Scaffold-GS#57]
Thanks for the excellent work. 
I have watched the talk given by Dr.Lu. But I am confused about the term "observation time" mentioned in 1:11:09 in the video 
https://www.bilibili.com/video/BV1gs421T7u9/?spm_id_from=333.999.0.0&vd_source=c86d7b50137491fd127fafc835d89fb6

The paper says the accumulated gradients or opacity over several iterations (e.g. 100) is the criteria. What does "observation time" mean? I can't find the corresponding codes for this term.
Is that means the accumulated gradients over 100 iterations is observed to be greater than a threshold for a specific time (e.g. 20)? So in this case, anchors only grow or get pruned at least 100*20 iterations later? 

If I get a wrong understanding, please correct me.

**Comment by inspirelt** [comment]
Please refer to https://github.com/city-super/Scaffold-GS/blob/47ac423fa25ac91c17380a6f138dbefd0d23b635/scene/gaussian_model.py#L686C59-L686C76 and https://github.com/city-super/Scaffold-GS/blob/47ac423fa25ac91c17380a6f138dbefd0d23b635/scene/gaussian_model.py#L705

, where the ```success_threshold``` corresponds to the observation threshold and ```*_denom``` are observation counts.
