### ISSUE TITLE
请问生成的ply文件分辨率和格式可以调整吗？

### ISSUE THREAD

**Issue by dandelion-chu** [city-super/Scaffold-GS#59]
您好，我运行了一下这个项目，看渲染图片效果感觉非常棒，然后也看到了生成的ply文件，请问这个ply文件可以调整分辨率吗？还有就是我看这个ply文件是没有rgb信息的，这个可以通过修改代码加入RGB色彩信息吗？

**Comment by inspirelt** [comment]
您好. 1) 可以通过调整渲染时的相机参数来获得不同分辨率的图片. 2) 因为我们的color都是通过feature和mlp在线解码出来的, 所以从原理和实践上来讲, ply中都是并没有rgb信息的.

**Comment by dandelion-chu** [comment]
> 您好. 1) 可以通过调整渲染时的相机参数来获得不同分辨率的图片. 2) 因为我们的color都是通过feature和mlp在线解码出来的, 所以从原理和实践上来讲, ply中都是并没有rgb信息的.

非常感谢您的答复，我下载了链接里面提到的SIBR_Viewer，pre-built window版本,也下载了exp1和exp2两个示例，结果exp2可以正常显示，但是exp1和我自己i训练出来的结果都无法显示，程序会挂掉，请问您知道是怎么一回事吗？
![1](https://github.com/city-super/Scaffold-GS/assets/105104235/f29dd4ed-52d6-41e3-84df-e4668cbf2837)

**Comment by dandelion-chu** [comment]
> 您好. 1) 可以通过调整渲染时的相机参数来获得不同分辨率的图片. 2) 因为我们的color都是通过feature和mlp在线解码出来的, 所以从原理和实践上来讲, ply中都是并没有rgb信息的.

对了，我对比了exp1，exp2和我自己训练的output结果里面的文件，发现exp2/ckpt/point_cloud/里面多了一个embedding_appearance.pt文件，其他的都没有，不知道是不是和这个文件有关系，不知道这个文件是如何生成的？麻烦了哈~~

**Comment by tongji-rkr** [comment]
This is because the second scene has illumination changes. `appearance_embedding` is an optional parameter used to model the difference information of each image.

**Comment by dandelion-chu** [comment]
> This is because the second scene has illumination changes. `appearance_embedding` is an optional parameter used to model the difference information of each image. And which CUDA version you use?

![3](https://github.com/city-super/Scaffold-GS/assets/105104235/735018ba-8913-47db-a5ee-06e294748c14)
![2](https://github.com/city-super/Scaffold-GS/assets/105104235/0eb00ae6-e244-44fd-b18b-1747640bfca1)
感谢您的回复，我之前CUDA版本有点低，然后现在更新到11.8了，exp1,exp2和我训练的mipnerf360/room场景都可以打开了，但是我训练的bungeenerf场景里面的rome仍然打不开，就像上图一样，打开界面是灰色的然后直接退出了，没有任何报错，我看了资源管理器里面，显存都没怎么使用，不知道您那边有试过吗？谢谢

**Comment by dandelion-chu** [comment]
> 可以给我截一下灰色的界面以及rome的文件结构吗

抱歉，给你添麻烦了，是我的问题，多亏了你的提醒，我又检查了下，发现有文件我搞错了，我重新把我训练的数据拷贝了一遍，现在可以了，多谢多谢

**Comment by dandelion-chu** [comment]
> 您好. 1) 可以通过调整渲染时的相机参数来获得不同分辨率的图片. 2) 因为我们的color都是通过feature和mlp在线解码出来的, 所以从原理和实践上来讲, ply中都是并没有rgb信息的.

再次打扰一下，请问咱们这套算法支持根据RGBD的数据，输出真实尺度的三维ply吗？谢谢哈~

**Comment by inspirelt** [comment]
没理解错的话，只要你的相机外参是真实尺度的，最终ply就是真实尺度的。

**Comment by dandelion-chu** [comment]
> 没理解错的话，只要你的相机外参是真实尺度的，最终ply就是真实尺度的。

好的好的，感谢答复~

**Comment by dandelion-chu** [comment]
> 没理解错的话，只要你的相机外参是真实尺度的，最终ply就是真实尺度的。

不好意思，请问使用自己的数据集的时候，在什么地方可以配置相机外参吗？我用colmap制作数据集然后去训练，结果也出来了，但是没发现有设置外参的地方，谢谢哈~

**Comment by dandelion-chu** [comment]
> 没理解错的话，只要你的相机外参是真实尺度的，最终ply就是真实尺度的。

您好，请问我训练自己的数据集的时候，有时候会出现错误提示OSError: [Errno 24] Too many open files
![1](https://github.com/city-super/Scaffold-GS/assets/105104235/08f63e26-0dc6-4ea7-a3a6-ef47ad5a84ae)
q请问您知道是什么原因吗？谢谢
