### ISSUE TITLE
Viewing training or rendering output

### ISSUE THREAD

**Issue by MrNeRF** [city-super/Scaffold-GS#6]
Hi, 
thx for the source code of this wonderful project. I managed to train a model although I stopped after 7k iterations.
How to view the output? The regular SIBR viewer crashes. The one you are including does not build

CMake Error at src/CMakeLists.txt:79 (add_subdirectory):
  add_subdirectory given source "core/view" which is not an existing
  directory.

render.py gives: FileNotFoundError: [Errno 2] No such file or directory: 'outputs/truck/train/ours_7000/renders/00000.png'

Thx

**Comment by haksorus** [comment]
Hello, @MrNeRF
Which viewer exactly did you find to be functional?
Thank you!

**Comment by MrNeRF** [comment]
None, at least not after training. But you can run the training and connect the remote app provided by the SIBR viewer.

**Comment by MickShen7558** [comment]
Hello @MrNeRF 
I tried to connect the SIBR remote viewer, but I could only see the point clouds. Did you see a rendering of the Gaussians?
Thank you!

**Comment by MrNeRF** [comment]
Hey yes. I just started the remote viewer. When you train, it connects automatically. You should see how the 3D scene emerges after a view iterations.

**Comment by cv-lab-x** [comment]
> Hey yes. I just started the remote viewer. When you train, it connects automatically. You should see how the 3D scene emerges after a view iterations.

hi, did the realtime viewer work? i just get the errors:
 LINE 720, FUNC sibr::GaussianView::onRenderIBR
                        A CUDA error occurred during rendering:an illegal memory access was encountered. Please rerun in Debug to find the exact line!

**Comment by inspirelt** [comment]
Hi, @cv-lab-x , we provide a viewer for Scaffold-GS. Please check https://github.com/city-super/Scaffold-GS/tree/main/SIBR_viewers.

**Comment by EarltShirt** [comment]
Hello @MrNeRF,
How did you launch the remote Gaussian renderer in order to be able to visualize the rendered gaussians and not only the point cloud ? I'm asking because the realtime viewer doesn't launch, and when launching the remote Gaussian viewer the original point cloud is visible but nothing else ..

**Comment by EarltShirt** [comment]
Finally all good, just saw that train.sh (which is launched by ALL other bash scripts) sets the port randomly. So  the SIBR Viewer won't connect unless you know it. Either echo the port number in the train.sh script and add the port number to the execution of the SIBR Viewer : `./SIBR_viewers/bin/SIBR_remoteGaussian_app.exe --port <port number>` or set the port number to 6009 manually in the train.sh file : 

```bash
function rand(){
    min=$1
    max=$(($2-$min+1))
    num=$(date +%s%N)
    echo $(($num%$max+$min))  
}

port=6009

lod=0
iterations=30_000
warmup="False"
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -l|--logdir) logdir="$2"; shift ;;
        -d|--data) data="$2"; shift ;;
        --lod) lod="$2"; shift ;;
        --gpu) gpu="$2"; shift ;;
        --warmup) warmup="$2"; shift ;;
        --voxel_size) vsize="$2"; shift ;;
        --update_init_factor) update_init_factor="$2"; shift ;;
        --appearance_dim) appearance_dim="$2"; shift ;;
        --ratio) ratio="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

time=$(date "+%Y-%m-%d_%H:%M:%S")

echo "Port: $port"

if [ "$warmup" = "True" ]; then
    python train.py --eval -s data/${data} --lod ${lod} --gpu ${gpu} --voxel_size ${vsize} --update_init_factor ${update_init_factor} --appearance_dim ${appearance_dim} --ratio ${ratio} --warmup --iterations ${iterations} --port $port -m outputs/${data}/${logdir}
else
    python train.py --eval -s data/${data} --lod ${lod} --gpu ${gpu} --voxel_size ${vsize} --update_init_factor ${update_init_factor} --appearance_dim ${appearance_dim} --ratio ${ratio} --iterations ${iterations} --port $port -m outputs/${data}/${logdir}
fi
```
