### ISSUE TITLE
Flowers和Treehill两个场景的storage数据

### ISSUE THREAD

**Issue by zsz-pro** [city-super/Scaffold-GS#61]
Nice work!
![image](https://github.com/city-super/Scaffold-GS/assets/61933660/23abd78d-f843-44bd-b8e3-9766844acf01)
想问下附录里3DGS的storage数据您是怎么知道的？方便的话您可以直接告诉我一下Flowers和Treehill两个场景的storage数据吗？不好意思我自己实在没找到

**Comment by inspirelt** [comment]
通过du -sh 来看的. storage: flowers->217MB, treehill->209MB, 供参考.

**Comment by zsz-pro** [comment]
谢谢！
