### ISSUE TITLE
Question about "voxel_visible_mask"

### ISSUE THREAD

**Issue by WeihangLiu2024** [city-super/Scaffold-GS#62]
I get confused about anchors pre-filter before rendering.
Referring to:
https://github.com/city-super/Scaffold-GS/blob/47ac423fa25ac91c17380a6f138dbefd0d23b635/render.py
and in line 49
`        voxel_visible_mask = prefilter_voxel(view, gaussians, pipeline, background)
`
The mask here seems to be calculated by projecting anchors to 2D space, which is invalid as there is no rotations for anchors. So what does "rotations" stand for in https://github.com/city-super/Scaffold-GS/blob/47ac423fa25ac91c17380a6f138dbefd0d23b635/gaussian_renderer/__init__.py line 232
`    radii_pure = rasterizer.visible_filter(means3D = means3D,
        scales = scales[:,:3],
        rotations = rotations,
        cov3D_precomp = cov3D_precomp)`
        
 Thanks and looking forward to your reply.

**Comment by inspirelt** [comment]
We kept an initial rotation for each anchor for future's potential calling. In current version, it's nearly useless.
