### ISSUE TITLE
how to make scaffold-gs become isotropy ?

### ISSUE THREAD

**Issue by BINOFL** [city-super/Scaffold-GS#64]
I change the GaussianModel's get_scaling defination, the scale is changed from `(N,6)` to `(N,2)` and when i store the ply, i make it isotropic, like:
```
        # scale = self._scaling.detach().cpu().numpy()  # (N, 6)
        scale = self._scaling.repeat(1, 3)[:, [0, 2, 4, 1, 3, 5]].detach().cpu().numpy()  # (N, 6)
        rotation = self._rotation.detach().cpu().numpy()  # (N, 4)
```

but when i use sibr viewer to see the scene, it is still anisotropy, can you help me with this ?

**Comment by inspirelt** [comment]
The output from MLP is still anisotropy. You should modify it as well.

**Comment by BINOFL** [comment]
thanks, it solved
