### ISSUE TITLE
implement Scaffold-GS in gsplat for nerstudio project

### ISSUE THREAD

**Issue by szhang963** [city-super/Scaffold-GS#69]
Did some guys implement the Scaffold-GS in gsplat for nerfstudio project？
Or, some suggestions for implementing this?
Thank you in advance.

**Comment by tongji-rkr** [comment]
We will develop a general framework that uses gspat for rendering.

**Comment by tongji-rkr** [comment]
We propose Octree-AnyGS, a general anchor-based framework that supports explicit Gaussians (2D-GS, 3D-GS) and neural Gaussians (Scaffold-GS). Additionally, Octree-GS has been adapted to the aforementioned Gaussian primitives, enabling Level-of-Detail representation for large-scale scenes. This framework holds potential for application to other Gaussian-based methods. Please refer to https://github.com/city-super/Octree-AnyGS.
