### ISSUE TITLE
Why the new_scaling repeated ?

### ISSUE THREAD

**Issue by ljh12401** [city-super/Scaffold-GS#79]
hello, thanks for your excellent work! 

I was wondering why the new_scaling in your code is repeated (1,2), should't it be 3 rather than 6?

https://github.com/city-super/Scaffold-GS/blob/b9e6220d63fb66caf9b8dda05653d32a4a4fe38a/scene/gaussian_model.py#L638

thanks again and look forward to your reply!

**Comment by tongji-rkr** [comment]
#58

**Comment by ljh12401** [comment]
thanks a lot!
