### ISSUE TITLE
merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

### ISSUE THREAD

**Issue by zsz-pro** [city-super/Scaffold-GS#8]
Thanks for your great work ！

When I run your code with torch==1.10.0+cu111, I encounter the error below. However, mip-splatting runs fine. So, is this a version-related issue?
![image](https://github.com/city-super/Scaffold-GS/assets/61933660/66ea7003-ac2a-43e6-9da5-6152eeab372d)

**Comment by zsz-pro** [comment]
Thanks for your time！I‘ll try it！

**Comment by zsz-pro** [comment]
不好意思再打扰下，可以问下你驱动的版本吗

**Comment by inspirelt** [comment]
Driver Version: 470.103.01.

**Comment by zsz-pro** [comment]
Thanks
