### ISSUE TITLE
您好，对于没有拍摄的角度很多虚影，请问这个有没有方法处理啊？

### ISSUE THREAD

**Issue by dandelion-chu** [city-super/Scaffold-GS#80]
您好，我重建了房间场景，自动播放模式查看很不错，在拍摄位置和角度感觉效果很好，很清晰；但是随意拖动三维场景的话，就可以看到很多虚影，请问这种情况有没有办法处理呀？谢谢
![3](https://github.com/user-attachments/assets/dbd79b84-2ebb-47b0-8587-f0a7315827a7)

**Comment by tongji-rkr** [comment]
我认为是拍的不够密或者位姿不准，3DGS的结果怎么样

**Comment by dandelion-chu** [comment]
> 我认为是拍的不够密或者位姿不准，3DGS的结果怎么样

您说的是训练之后评估的PSNR，SSIM这些指标吗？我这边因为显存不足，所以把data_device = "cpu"，后面评估的数据看不到，只能看到打印前面的
![image](https://github.com/user-attachments/assets/0ab0f469-ecc7-4191-8840-af50794246dc)

**Comment by cskrren** [comment]
I refer to the qualitative results of vallina 3D-GS in new viewpoints like
![image](https://github.com/user-attachments/assets/5d73fa13-f904-44a2-a1a9-ef0ccbc43196)
