### ISSUE TITLE
您好，请教下使用SLAM来代替COLMAP重建模型的问题

### ISSUE THREAD

**Issue by dandelion-chu** [city-super/Scaffold-GS#81]
您好，我这边计划使用SLAM计算出来的结果来代替colmap生成的模型文件，然后研究了camera.txt，images.txt和points.txt的格式，我这边也参考格式将图片和位姿等信息填入，程序可以正常训练并输出ply结果，但是这个结果用SIBR查看发现splat模式没有色彩信息，如下图所示
![3](https://github.com/user-attachments/assets/cf252fa6-8b3b-4317-93ff-1f1cd1956c27)
![4](https://github.com/user-attachments/assets/263762d2-22a8-44cb-9232-c1dd47ad95c7)
我对比了模型txt文件，images.txt里面没有填写关键点的信息，然后points3D.ply我是直接用slam输出的点云结果转换的，包含了xyz，nxnynz,rgb等信息
![5](https://github.com/user-attachments/assets/d30cda59-5ab5-47fb-8a04-9fae925cdc88)
![6](https://github.com/user-attachments/assets/c610baa8-14ec-4cc9-8569-94c08bfb59a7)
请问您知道大概是哪里可能导致的问题吗？多谢您的指教~

**Comment by inspirelt** [comment]
您好. 请问您使用的是我们提供的viewer吗? Scaffold GS的模型文件不支持3DGS的原生Viewer

**Comment by dandelion-chu** [comment]
> 您好. 请问您使用的是我们提供的viewer吗? Scaffold GS的模型文件不支持3DGS的原生Viewer

对的，是使用的项目提供的viewer，我之前训练用colmap计算得到的模型文件是可以正常查看的，怀疑还是自己生成的那几个images.txt,camera.txt和points3D.ply模型文件有问题，就是还不确定问题出现的原因，所以想请教一下你们有没有排查的思路可以指点一下，多谢哈~

**Comment by dandelion-chu** [comment]
> 您好. 请问您使用的是我们提供的viewer吗? Scaffold GS的模型文件不支持3DGS的原生Viewer
[parkpart.zip](https://github.com/user-attachments/files/17348563/parkpart.zip)

这个是我的输入模型，但是图片太大了，所以只打包了部分的，训练的时候速度很快，十几分钟就结束了，之前正常训练的话都要四五十分钟；如果方便还麻烦百忙之中帮忙看看我这输入的哪部分数据弄错了，谢谢~~

**Comment by dandelion-chu** [comment]
> 您好. 请问您使用的是我们提供的viewer吗? Scaffold GS的模型文件不支持3DGS的原生Viewer

你好，已经解决了，是colmap的坐标系使用的是相机坐标系，和SLAM常用的世界坐标系不一致，变换image.txt里面的图片坐标之后就可以了，麻烦了哈~
