### ISSUE TITLE
About feature bank not used

### ISSUE THREAD

**Issue by ALEX5874** [city-super/Scaffold-GS#84]
Hallo, you have done great work!
I have a question: why the feat_bank in your code is all set into False? In the paper, the feature bank seems to be a critical part of initialization of the anchor, why you abondon it?

**Comment by inspirelt** [comment]
Hi. The feat bank works in some scenes. However, we want to keep our method as simple as possible, so we disable it by default.

**Comment by chaibosong** [comment]
但是如果启用use_feat_bank，会报错：AttributeError: 'GaussianModel' object has no attribute 'mlp_feature_bank'，这个错误应该怎么解决

**Comment by cskrren** [comment]
We simplified the code later on, and this feature has been abandoned.
