### ISSUE TITLE
About Enhanced Wall Reconstruction Quality in Scaffold-GS

### ISSUE THREAD

**Issue by LabubuJ** [city-super/Scaffold-GS#87]
Hello, thank you for your excellent work. 
The reconstruction quality of Scaffold-GS is truly impressive. I would like to know why Scaffold-GS achieves such a significant visual quality improvement in wall reconstruction compared to 3DGS. 3DGS often introduces many flaws when reconstructing walls and other planar surfaces, manifesting as heavy shadows in certain areas. However, Scaffold-GS can reconstruct clean walls. Is this improvement due to the viewpoint-dependent properties of structured 3D Gaussians, or does the anchor point bring a larger number of 3D Gaussians? 
I would appreciate your insights. Thank you!

**Comment by inspirelt** [comment]
Hello, I think the reason are two-fold (at least): 1. the more powerful representative ability from view-dependent properties; 2. the 'anchor + offset' based densification potentially has a better ability to capture geometry.

**Comment by SteamAndMagic** [comment]
Thank you very much for your reply.

**Comment by LabubuJ** [comment]
Thanks for your response!
