### ISSUE TITLE
Prune points

### ISSUE THREAD

**Issue by bmikaili** [city-super/Scaffold-GS#9]
Has anyone tried combining this approach with a prune step like in https://github.com/VITA-Group/LightGaussian?

**Comment by inspirelt** [comment]
This is an interesting idea. I try to set a more strict pruning rule during training to simulate the LightGaussian (not perfectly consistent). For simplicity, I set ```self.min_opacity``` to ```0.005```(original), ```0.2```, ```0.5```. The results on ```Tandt/truck``` are as follows:

<img width="459" alt="image" src="https://github.com/city-super/Scaffold-GS/assets/9450147/65504e14-54d7-4cbe-8ae7-ee91615cfdb0">


With a more strict rule (larger min_opacity), Scaffold-GS enjoys a smaller storage and faster speed, at the sacrifice of LPIPS. This is just a simple and not very rigorous exploration, further conclusions are welcome in the future.
