### ISSUE TITLE
Generation of Feature Bank 

### ISSUE THREAD

**Issue by Sanctuary345** [city-super/Scaffold-GS#90]
Can you tell me where the code for Generation of Feature Bank is in Fig10, I can't seem to find the corresponding section in gaussian_model.py.

**Comment by Sanctuary345** [comment]
I found the relevant code in gaussian_renderer

**Comment by chaibosong** [comment]
最近在学习这篇论文代码，在debug时，并没有进行use_feat_bank操作，如果设置为true，会报错AttributeError: 'GaussianModel' object has no attribute 'mlp_feature_bank'，这个错误怎么解决
