### ISSUE TITLE
 the number of 3D Gaussians

### ISSUE THREAD

**Issue by Sanctuary345** [city-super/Scaffold-GS#93]
How do I know the number of 3D Gaussians in a point cloud model after training?

**Comment by cskrren** [comment]
You can use SIBR viewer to visualize `.ply` files.

**Comment by Sanctuary345** [comment]
Can I use the method of evaluating the total number of Gaussians in octree-gs to get the total number of Gaussians in scaffold-gs?

**Comment by DuHao55** [comment]
Can I use the method of evaluating the total number of Gaussians in octree-gs to get the total number of Gaussians in scaffold-gs?

**Comment by cskrren** [comment]
I think so. You can ask me if you have any questions.

**Comment by Sanctuary345** [comment]
Thanks for the answer, I'll try it.
